### ISSUE TITLE
Report: pushstore

### ISSUE THREAD

**Issue by timotoots** [timotoots/iphonebackuptools#7]
Python example to port to our project:
https://github.com/jakev/pushstore-parser

Should parse all PushStore files and include the same fields as in python version. As we parse all notifications for all apps, we should add the application name and id.
*

**Comment by aguerere** [comment]
This is working for iOS <11.0 here: https://github.com/timotoots/iphonebackuptools/tree/feature/pushstore

Ported from https://github.com/jakev/pushstore-parser/blob/master/pushstore_parser/pushstore_parser.py

**Comment by aguerere** [comment]
PR created https://github.com/richinfante/iphonebackuptools/pull/25
